import type { CropPreset, EditorConfig } from "../types/Editor";
import { TABS, TOOLS } from "react-filerobot-image-editor";

const cropPresets: CropPreset[] = [
  {
    titleKey: "square",
    descriptionKey: "1:1",
    ratio: 1,
  },
  {
    titleKey: "portrait",
    descriptionKey: "3:4",
    ratio: 3 / 4,
  },
];

export const createEditorConfig = (imageUrl: string): EditorConfig => ({
  savingPixelRatio: 5,
  previewPixelRatio: 5,
  source: imageUrl,
  defaultSavedImageType: "webp",
  defaultSavedImageName: "edited-image",
  annotationsCommon: {
    fill: "#ff0000",
    stroke: "#ff0000",
    strokeWidth: 10,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowBlur: 0,
    shadowColor: "#000000",
    shadowOpacity: 1,
    opacity: 1,
  },
  Pen: {
    strokeWidth: 10,
    tension: 0.5,
    lineCap: "round",
    selectAnnotationAfterDrawing: true,
  },
  theme: {
    palette: {
      "txt-primary": "#C0C0C0",
      "txt-secondary": "#b3b3b3",
      "txt-secondary-invert": "#4d4d4d",
      "txt-placeholder": "#666666",
      "txt-warning": "#ffcc00",
      "txt-error": "#ff4d4d",
      "txt-info": "#4da6ff",
      "accent-primary": "#1a73e8",
      "accent-primary-hover": "#1669c1",
      "accent-primary-active": "#C0C0C1",
      "accent-primary-disabled": "#4d90fe",
      "accent-secondary-disabled": "#b3d4fc",
      "accent-stateless": "#565656",
      "accent-stateless_0_4_opacity": "rgba(255, 255, 255, 0.4)",
      accent_0_5_5_opacity: "rgba(255, 255, 255, 0.55)",
      accent_0_5_opacity: "rgba(255, 255, 255, 0.5)",
      accent_0_7_opacity: "rgba(255, 255, 255, 0.7)",
      accent_1_2_opacity: "rgba(255, 255, 255, 0.12)",
      accent_1_8_opacity: "rgba(255, 255, 255, 0.18)",
      accent_2_8_opacity: "rgba(255, 255, 255, 0.28)",
      accent_4_0_opacity: "rgba(255, 255, 255, 0.4)",
      "bg-grey": "#333333",
      "bg-stateless": "#1a1a1a",
      "bg-active": "#4d4d4d",
      "bg-base-light": "#262626",
      "bg-base-medium": "#1a1a1a",
      "bg-primary": "#1a73e8",
      "bg-primary-light": "#4d90fe",
      "bg-primary-hover": "#1669c1",
      "bg-primary-active": "#1458a6",
      "bg-primary-stateless": "#1a73e8",
      "bg-primary-0-5-opacity": "rgba(26, 115, 232, 0.5)",
      "bg-secondary": "#333333",
      "bg-hover": "#4d4d4d",
      "bg-green": "#34a853",
      "bg-green-medium": "#66bb6a",
      "bg-blue": "#4285f4",
      "bg-red": "#ea4335",
      "bg-red-light": "#ff6f61",
      "background-red-medium": "#ff4d4d",
      "bg-orange": "#fbbc05",
      "bg-tooltip": "#333333",
      "icon-primary": "#C0C0C3",
      "icons-primary-opacity-0-6": "rgba(255, 255, 255, 0.6)",
      "icons-secondary": "#b3b3b3",
      "icons-placeholder": "#666666",
      "icons-invert": "#4d4d4d",
      "icons-muted": "#999999",
      "icons-primary-hover": "#C0C0C4",
      "icons-secondary-hover": "#b3b3b3",
      "btn-primary-text": "#C0C0C5",
      "btn-primary-text-0-6": "rgba(255, 255, 255, 0.6)",
      "btn-primary-text-0-4": "rgba(255, 255, 255, 0.4)",
      "btn-disabled-text": "#666666",
      "btn-secondary-text": "#b3b3b3",
      "link-primary": "#1a73e8",
      "link-stateless": "#C0C0C6",
      "link-hover": "#1669c1",
      "link-active": "#1458a6",
      "link-muted": "#999999",
      "link-pressed": "#1458a6",
      "borders-primary": "#4d4d4d",
      "borders-primary-hover": "#666666",
      "borders-secondary": "#b3b3b3",
      "borders-strong": "#C0C0C7",
      "borders-invert": "#4d4d4d",
      "border-hover-bottom": "#666666",
      "border-active-bottom": "#C0C0C8",
      "border-primary-stateless": "#4d4d4d",
      "borders-disabled": "#666666",
      "borders-button": "#4d4d4d",
      "borders-item": "#4d4d4d",
      "borders-base-light": "#262626",
      "borders-base-medium": "#1a1a1a",
      "borders-green": "#34a853",
      "borders-green-medium": "#66bb6a",
      "borders-red": "#ea4335",
      "active-secondary": "#4d4d4d",
      "active-secondary-hover": "#666666",
      tag: "#1a73e8",
      "states-error-disabled-text": "#ff4d4d",
      error: "#ea4335",
      "error-0-28-opacity": "rgba(234, 67, 53, 0.28)",
      "error-0-12-opacity": "rgba(234, 67, 53, 0.12)",
      "error-hover": "#ff6f61",
      "error-active": "#ff4d4d",
      success: "#34a853",
      "success-hover": "#66bb6a",
      "success-Active": "#34a853",
      warning: "#fbbc05",
      "warning-hover": "#ffcc00",
      "warning-active": "#ffcc00",
      info: "#4285f4",
      modified: "#ffcc00",
      red: "#ea4335",
      orange: "#fbbc05",
      salad: "#34a853",
      green: "#34a853",
      blue: "#4285f4",
      indigo: "#3f51b5",
      violet: "#9c27b0",
      pink: "#e91e63",
      "gradient-right": "linear-gradient(to right, #1a1a1a, #333333)",
      "extra-0-3-overlay": "rgba(0, 0, 0, 0.3)",
      "gradient-right-active": "linear-gradient(to right, #1a1a1a, #4d4d4d)",
      "gradient-right-hover": "linear-gradient(to right, #1a1a1a, #666666)",
      "extra-0-5-overlay": "rgba(0, 0, 0, 0.5)",
      "extra-0-7-overlay": "rgba(0, 0, 0, 0.7)",
      "extra-0-9-overlay": "rgba(0, 0, 0, 0.9)",
      "red-0-1-overlay": "rgba(234, 67, 53, 0.1)",
      "orange-0-1-overlay": "rgba(251, 188, 5, 0.1)",
      "accent-0-8-overlay": "rgba(26, 115, 232, 0.8)",
      "green-0-2-Overlay": "rgba(52, 168, 83, 0.2)",
      "white-0-7-8-overlay": "rgba(255, 255, 255, 0.78)",
      link: "#1a73e8",
      camera: "#C0C0C9",
      "google-drive": "#C0C0CA",
      dropbox: "#C0C0CB",
      "one-drive": "#C0C0CC",
      device: "#C0C0CD",
      instagram: "#C0C0CE",
      "free-images": "#C0C0CF",
      "free-icons": "#C0C0D0",
      canvas: "#C0C0D1",
      box: "#C0C0D2",
      "screen-cast": "#C0C0D3",
      unsplash: "#C0C0D4",
      "light-shadow": "rgba(0, 0, 0, 0.2)",
      "medium-shadow": "rgba(0, 0, 0, 0.4)",
      "large-shadow": "rgba(0, 0, 0, 0.6)",
      "x-large-shadow": "rgba(0, 0, 0, 0.8)",
    },
    typography: {
      fontFamily: "Inter, system-ui, sans-serif",
    },
  },

  Text: {
    text: "Add text...",
    fonts: [
      { label: "Arial", value: "Arial" },
      { label: "Helvetica", value: "Helvetica" },
      { label: "Inter", value: "Inter" },
      { label: "Times New Roman", value: "Times New Roman" },
      { label: "Courier New", value: "Courier New" },
      { label: "Georgia", value: "Georgia" },
      { label: "Verdana", value: "Verdana" },
      { label: "Geneva", value: "Geneva" },
      { label: "Trebuchet MS", value: "Trebuchet MS" },
      { label: "Arial Black", value: "Arial Black" },
      { label: "Impact", value: "Impact" },
      { label: "Comic Sans MS", value: "Comic Sans MS" },
      { label: "Lucida Console", value: "Lucida Console" },
      { label: "Tahoma", value: "Tahoma" },
      { label: "Palatino Linotype", value: "Palatino Linotype" },
      { label: "Book Antiqua", value: "Book Antiqua" },
      { label: "Arial Narrow", value: "Arial Narrow" },
      { label: "Century Gothic", value: "Century Gothic" },
      { label: "Lucida Sans Unicode", value: "Lucida Sans Unicode" },
      { label: "Garamond", value: "Garamond" },
    ],
  },
  translations: {
    profile: "Profile",
    coverPhoto: "Cover Photo",
    facebook: "Facebook",
    socialMedia: "Social Media",
    classicTv: "Classic TV",
    wide: "Widescreen",
    square: "Square",
    portrait: "Portrait",
  },
  Crop: {
    presetsItems: cropPresets,
    autoResize: true,
  },
  observePluginContainerSize: true,
  showCanvasOnly: false,
  defaultTabId: TABS.ANNOTATE,
  defaultToolId: TOOLS.PEN,
});
